Repository AlejandraLLI/pds-2019, pull requests merged in 2019-11, with the labels that each got.

#6 Adding the eempty pyproject.toml file
  pyproject.toml
Labels: stucture

#9 Modifying the create_schemas.sql file
  sql/create_schemas.sql
Labels: SQL files

#10 adding create_raw_tables.sql file to create raw tables from moma files
  sql/create_raw_tables.sql
Labels: SQL files

#13 First update of README File
  README.md
Labels: documentation

#14 Adding settings.toml file
  config/settings.toml
Labels: stucture

#16 modify moma.py with connection and create_schemas, adding __init__.py
  moma/__init__.py
  moma/moma.py
Labels: python

#18 modifying create_schemas in moma.py file
  moma/moma.py
Labels: python

#20 Making changes to paths in settings.toml and moma.py
  config/settings.toml
  moma/moma.py
Labels: SQL files, stucture

#22 adding create_raw_tables in moma.py file
  moma/moma.py
Labels: python

#25 modifying create_raw_tables.sql file
  sql/create_raw_tables.sql
Labels: SQL files

#26 Adding load_moma command to moma.py
  moma/moma.py
Labels: python

#28 modifying create_raw_tables.sql file
  sql/create_raw_tables.sql
Labels: SQL files

#31 modifying create_raw_tables.sql file
  sql/create_raw_tables.sql
Labels: SQL files

#33 Changing field separatori in load_moma comand in moma.py file
  moma/moma.py
Labels: python
